server:
  port: 8989
  mailSender:  
  passSender:  
  otpLength: 6

mongodb:
  url:  
  dbName: DB_Data
  
  tripadvior-travel-review: tripadvior_travel.review
  tripadvior-travel-data: tripadvior_travel.data
  tripadvior-hotel-review: tripadvior_hotel.review
  tripadvior-hotel-data: tripadvior_hotel.data
  tripadvior-shop-review: tripadvior_shop.review
  tripadvior-shop-data: tripadvior_shop.data

  maxpool: 5
  minpool: 1
